  
name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@master #Github Action version
        with:
          project_name: Test 1
          base_uri: https://eu.ast.checkmarx.net/
          cx_apikey: ${{ secrets.KEY }}
          scan_types: sast
