name: SCA Resolver Example

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download SCA Resolver
        run: |
          wget https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz
          tar -xzvf ScaResolver-linux64.tar.gz
          rm -rf ScaResolver-linux64.tar.gz
          
      - name: Run SCA Resolver in offline mode
        run: |
          ./ScaResolver offline -s . -r .cxsca-results.json
          rm -rf ./ScaResolver
      
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: https://ast-master.dev.cxast.net/
          cx_tenant: galactica
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }} 
          additional_params: >-
            --tags product_id:123456789-123456-789654123
