name: Tester

on: [pull_request,workflow_dispatch]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Checkmarx AST CLI Action
        uses: andregcx/ast-github-action@feature/handle_cancel_scan 
        with:
          base_uri: https://ast-master.dev.cxast.net/
          cx_tenant: galactica
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}

