name: Tester

on: [pull_request,workflow_dispatch]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main 
        with:
          base_uri: https://ast.ppe.cxast.net/
          cx_tenant: research_tenant
          cx_client_id: andre
          cx_client_secret: e88ecfcf-9301-431d-ae40-6cf854b0ac50

